#!/usr/bin/env bash
# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
#
# One-time vendoring script for the OFFLINE Ascend (Atlas A3 / 910B) build.
#
# Populates 3rdparty/ with every source tree that scripts/build_ascend_a3.sh
# needs, so the build host requires NO network access to github.com /
# gitcode.com / PyPI at build time. Run this ONCE on a networked machine
# (Linux/WSL/macOS preferred; plain Windows git-bash also works -- this script
# compensates for the two things Windows checkouts lose: symlinks are dropped
# using the authoritative git index, and exec bits are restored in the index
# via `git update-index --chmod=+x`), then review and COMMIT the result:
#
#   bash scripts/vendor_deps.sh
#   git status && git diff --cached --stat | tail
#   git commit -m "vendor: offline Ascend build dependencies"
#   git push   # ~a few hundred MB pack, one time
#
# What lands in 3rdparty/ (see 3rdparty/VENDORED.md, regenerated by this script):
#
#   llvm-project/     llvm/llvm-project @ fad3272 (the commit recorded in
#                     triton-ascend's cmake/llvm-hash.txt) with triton-ascend's
#                     third_party/ascend/llvm_patch/fad3272.patch PRE-APPLIED.
#                     Trimmed to llvm/ + mlir/ + lld/ (the subprojects the build
#                     uses, LLVM_ENABLE_PROJECTS="mlir;llvm;lld"); test suites
#                     removed (built with -DLLVM_INCLUDE_TESTS=OFF
#                     -DMLIR_INCLUDE_TESTS=OFF, which keeps FileCheck -- it is
#                     gated by LLVM_INCLUDE_UTILS -- and drops only llvm-lit,
#                     which nothing in this flow consumes).
#   triton-ascend/    triton-lang/triton-ascend @ the submodule-pinned commit
#                     (bfd8f55), PRISTINE: python/setup.py git-applies
#                     3rdparty/triton-ascend.patch at build time (verified by
#                     this script's preflight to apply to this exact commit).
#                     Its inner submodule third_party/ascend/AscendNPU-IR is
#                     populated at triton-ascend's pinned commit (pristine;
#                     setup.py applies 3rdparty/AscendNPU-IR.patch to it).
#   AscendNPU-IR/     gitcode Ascend/AscendNPU-IR @ the same pinned commit,
#                     for the standalone bisheng build (step 3 of
#                     build_ascend_a3.sh). Its third-party/llvm-project is
#                     populated at npuir's pinned commit with npuir's own
#                     build-tools/patches/llvm-project/*.patch PRE-APPLIED
#                     (same sorted sequence as upstream's --apply-patches,
#                     applied with `git apply --ignore-whitespace` instead of
#                     `patch -p1 --merge` for Windows-git-bash compatibility;
#                     content-identical result) and trimmed as above, so the
#                     build runs WITHOUT --apply-patches. third-party/torch-mlir
#                     is intentionally absent (BUILD_TORCH_MLIR=OFF in our flow;
#                     --build-torch-mlir is NOT supported offline).
#   shmem/            gitcode cann/shmem @ the submodule-pinned commit
#                     (81c95bad), PRISTINE. The `-python_extension` build path
#                     needs no catlass/googletest/json downloads (verified in
#                     its scripts/build.sh; those only fire for -uttests /
#                     -examples / -python_example / -full / SOC_TYPE=Ascend950).
#   nlohmann-json/    nlohmann/json v3.11.3 release headers (include/ +
#                     single_include/), used via JSON_SYSPATH so setup.py's
#                     TRITON_OFFLINE_BUILD=1 path never reaches the network.
#
# Git surgery performed (idempotent):
#   * 3rdparty/triton-ascend and 3rdparty/shmem stop being submodules
#     (gitlinks removed from the index, .gitmodules sections dropped,
#     .git/modules/* cleaned).
#   * 3rdparty/.gitattributes pins `* text=auto eol=lf` so Windows checkouts
#     can never rewrite vendored sources/patches to CRLF.
#   * everything is `git add -f`'d (the root .gitignore has broad patterns like
#     `build`, `*.csv`, `tmp*` that would silently drop upstream files), then
#     upstream exec bits (mode 100755) are restored in the index.
#
# Env overrides:
#   FORCE=1        re-vendor trees that already exist
#   WORK=<dir>     scratch dir (default: mktemp -d; needs ~8 GB free)
#   KEEP_WORK=1    do not delete the scratch dir on exit
set -euo pipefail

# ---------------------------------------------------------------------------
# pins (cross-checked against the trees at runtime; see 3rdparty/VENDORED.md)
# ---------------------------------------------------------------------------
TA_URL="https://github.com/triton-lang/triton-ascend.git"
TA_SHA="${TA_SHA:-bfd8f55d124f0da70ef792cb8d9f759d7302bb26}"
LLVM_URL="https://github.com/llvm/llvm-project.git"
LLVM_SHA_EXPECTED="fad3272286528b8a491085183434c5ad4b59ab92"  # sanity check only
NPU_IR_URL="https://gitcode.com/Ascend/AscendNPU-IR.git"
SHMEM_URL="https://gitcode.com/cann/shmem.git"
SHMEM_SHA="${SHMEM_SHA:-81c95bad8b943fbcf99e1a9664350aa41a937588}"
JSON_URL="https://github.com/nlohmann/json/releases/download/v3.11.3/include.zip"
JSON_VERSION="3.11.3"

FORCE="${FORCE:-0}"
KEEP_WORK="${KEEP_WORK:-0}"

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="${WORK:-$(mktemp -d "${TMPDIR:-/tmp}/triton-dist-vendor.XXXXXX")}"

die() { echo "[ERROR] $*" >&2; exit 1; }
banner() { echo; echo ">>> $*"; }
[[ "${KEEP_WORK}" == "1" ]] || trap 'rm -rf "$WORK"' EXIT

# ---------------------------------------------------------------------------
# preflight
# ---------------------------------------------------------------------------
banner "vendor_deps: repo=$ROOT work=$WORK"
case "$(uname -s)" in
    Linux|Darwin) ;;
    MINGW*|MSYS*|CYGWIN*)
        echo "[WARN] Windows git-bash detected: symlinks will be dropped via the git index"
        echo "[WARN] and exec bits restored via 'git update-index --chmod=+x' (see step 7)"
        git config --get core.longpaths >/dev/null 2>&1 \
            || echo "[WARN] core.longpaths is not enabled globally -- LLVM checkouts may fail on deep paths"
        ;;
    *) die "unsupported platform: $(uname -s)" ;;
esac
for tool in git curl; do
    command -v "$tool" >/dev/null 2>&1 || die "$tool not installed"
done
# Windows: `python3` is often the Store stub -- probe each candidate for real
PYTHON_BIN=""
for cand in python3 python py; do
    if command -v "$cand" >/dev/null 2>&1 && "$cand" -c 'import zipfile' >/dev/null 2>&1; then
        PYTHON_BIN="$(command -v "$cand")"
        break
    fi
done
[[ -n "$PYTHON_BIN" ]] || die "no usable python3/python found (need zipfile module)"
echo "python: $PYTHON_BIN ($("$PYTHON_BIN" --version 2>&1))"
[[ -f "$ROOT/python/setup.py" ]] || die "$ROOT does not look like a Triton-distributed checkout"
# Make sure the repo's own patch files are LF in the worktree: a CRLF copy
# (e.g. a Windows checkout made before .gitattributes existed) makes every
# `git apply` below and in step 8 fail with "corrupt patch". A plain
# `git checkout --` is a no-op here (CRLF worktree == LF blob counts as
# unmodified under autocrlf), so remove the files first.
rm -f "$ROOT/3rdparty/triton-ascend.patch" "$ROOT/3rdparty/AscendNPU-IR.patch"
git -C "$ROOT" checkout -- 3rdparty/triton-ascend.patch 3rdparty/AscendNPU-IR.patch
if command -v nproc >/dev/null 2>&1; then
    df -h "$WORK" | tail -1
    echo "(need ~8 GB free in the scratch filesystem)"
fi

# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------
fetch_pin() {  # $1=url $2=sha $3=dest (keeps .git for later ls-tree/patch ops)
    local url="$1" sha="$2" dest="$3"
    if [[ -d "$dest/.git" && "$(git -C "$dest" rev-parse HEAD 2>/dev/null)" == "$sha" ]]; then
        echo "  cached: $dest @ ${sha:0:9} (resetting tree)"
        # reset to pristine state so patches can be replayed after a failed run
        git -C "$dest" checkout -q -f HEAD
        git -C "$dest" clean -qfd
        return
    fi
    echo "  fetching ${sha:0:9} from $url"
    rm -rf "$dest"; mkdir -p "$dest"
    git -C "$dest" init -q
    git -C "$dest" config core.longpaths true
    git -C "$dest" config core.autocrlf false
    git -C "$dest" config core.symlinks false   # materialize symlinks; dropped via the index later
    git -C "$dest" remote add origin "$url"
    git -C "$dest" fetch -q --depth=1 origin "$sha"
    git -C "$dest" checkout -q -f FETCH_HEAD
    [[ "$(git -C "$dest" rev-parse HEAD)" == "$sha" ]] || die "fetch_pin: $dest is not at $sha"
}

capture_exec_list() {  # $1=clone dir $2=out list (paths relative to $1, upstream mode 100755)
    git -C "$1" ls-files -s | while IFS=$'\t' read -r meta path; do
        case "$meta" in
            100755*) echo "$path" ;;
        esac
    done > "$2"
}

apply_exec_bits() {  # $1=list file $2=prefix under $ROOT (files must already be git-added)
    local list="$1" prefix="$2" filtered p n
    [[ -f "$list" ]] || return 0
    filtered="$list.filtered"
    : > "$filtered"
    while IFS= read -r p; do
        [[ -n "$p" && -e "$ROOT/$prefix/$p" ]] && echo "$prefix/$p" >> "$filtered"
    done < "$list"
    n=$(wc -l < "$filtered")
    if [[ "$n" -gt 0 ]]; then
        tr '\n' '\0' < "$filtered" | xargs -0 git -C "$ROOT" update-index --chmod=+x --
        echo "  exec bits (+x) restored on $n file(s) under $prefix/"
    fi
    rm -f "$filtered"
}

trim_llvm_tree() {  # $1=llvm-project root; keep llvm+mlir+lld, drop test suites
    local root="$1" e base l
    # Drop git-declared symlinks FIRST (while .git still exists): on Windows
    # they are materialized as fake regular files, so `find -type l` cannot
    # see them. Within the kept subprojects the only symlinks are three inert
    # llvm/utils/mlgo-utils helpers pointing into the dropped clang/ tree.
    if [[ -d "$root/.git" ]]; then
        while IFS= read -r l; do
            [[ -n "$l" ]] || continue
            echo "  trim: removing symlink $l"
            rm -f "$root/$l"
        done < <(git -C "$root" ls-files -s | awk -F'\t' '$1 ~ /^120000/ {print $2}')
    fi
    local keep=" llvm mlir lld LICENSE.TXT README.md "
    shopt -s dotglob
    for e in "$root"/*; do
        base="$(basename "$e")"
        [[ "$keep" == *" $base "* ]] || rm -rf "$e"
    done
    shopt -u dotglob
    # test suites: built with -DLLVM_INCLUDE_TESTS=OFF -DMLIR_INCLUDE_TESTS=OFF
    rm -rf "$root/llvm/test" "$root/llvm/unittests" "$root/mlir/test" "$root/mlir/unittests"
    # belt & braces: any real symlinks left (Linux checkouts)
    while IFS= read -r l; do
        echo "  trim: removing symlink ${l#"$root"/}"
        rm -f "$l"
    done < <(find "$root" -type l)
}

place_tree() {  # $1=src (with .git) $2=dest  -- copy without .git
    local src="$1" dest="$2"
    rm -rf "$dest"; mkdir -p "$(dirname "$dest")"
    cp -a "$src" "$dest"
    rm -rf "$dest/.git"
}

write_vendor_sha() {  # $1=dir $2=url $3=sha $4=extra note
    printf 'url=%s\nsha=%s\nvendored=%s\nnote=%s\n' "$2" "$3" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$4" > "$1/.vendor-sha"
}

exists_skip() {  # $1=dir -> 0 (skip) if present and FORCE!=1
    [[ "$FORCE" == "1" || ! -e "$1" ]] && return 1
    echo "  exists, skipping (FORCE=1 to re-vendor): $1"
    return 0
}

# ---------------------------------------------------------------------------
# step 0: git surgery -- de-submodule triton-ascend & shmem
# ---------------------------------------------------------------------------
banner "step 0: removing 3rdparty/{triton-ascend,shmem} submodule entries"
cd "$ROOT"
git submodule deinit -f 3rdparty/triton-ascend 3rdparty/shmem >/dev/null 2>&1 || true
for p in 3rdparty/triton-ascend 3rdparty/shmem; do
    if git ls-files --stage -- "$p" | grep -q '^160000'; then
        git update-index --force-remove "$p"
        echo "  removed gitlink from index: $p"
    fi
    git config -f .gitmodules --remove-section "submodule.$p" 2>/dev/null || true
done
rm -rf .git/modules/3rdparty/triton-ascend .git/modules/3rdparty/shmem

# ---------------------------------------------------------------------------
# step 1: triton-ascend (+ derive pins)
# ---------------------------------------------------------------------------
banner "step 1: triton-ascend @ ${TA_SHA:0:9}"
fetch_pin "$TA_URL" "$TA_SHA" "$WORK/ta"
capture_exec_list "$WORK/ta" "$WORK/exec-ta.list"

LLVM_SHA="$(tr -d '[:space:]' < "$WORK/ta/cmake/llvm-hash.txt")"
[[ "$LLVM_SHA" == "$LLVM_SHA_EXPECTED" ]] \
    || echo "[WARN] triton-ascend pins LLVM $LLVM_SHA (expected $LLVM_SHA_EXPECTED); continuing"
NPU_IR_SHA="$(git -C "$WORK/ta" ls-tree HEAD third_party/ascend/AscendNPU-IR | awk '{print $3}')"
[[ -n "$NPU_IR_SHA" ]] || die "could not read AscendNPU-IR pin from triton-ascend"
echo "  derived: LLVM=$LLVM_SHA"
echo "  derived: AscendNPU-IR=$NPU_IR_SHA"

LLVM_PATCHES=("$WORK/ta"/third_party/ascend/llvm_patch/*.patch)
[[ ${#LLVM_PATCHES[@]} -eq 1 ]] || die "expected exactly 1 patch in ta/third_party/ascend/llvm_patch/, got ${#LLVM_PATCHES[@]}"
LLVM_PATCH="${LLVM_PATCHES[0]}"

if ! exists_skip "$ROOT/3rdparty/triton-ascend/cmake/llvm-hash.txt"; then
    place_tree "$WORK/ta" "$ROOT/3rdparty/triton-ascend"
    write_vendor_sha "$ROOT/3rdparty/triton-ascend" "$TA_URL" "$TA_SHA" "pristine; 3rdparty/triton-ascend.patch applied by setup.py at build time"
fi

# ---------------------------------------------------------------------------
# step 2: AscendNPU-IR (inner copy for TA + standalone copy for step-3 build)
# ---------------------------------------------------------------------------
banner "step 2: AscendNPU-IR @ ${NPU_IR_SHA:0:9}"
fetch_pin "$NPU_IR_URL" "$NPU_IR_SHA" "$WORK/npuir"
capture_exec_list "$WORK/npuir" "$WORK/exec-npuir.list"
NPU_LLVM_SHA="$(git -C "$WORK/npuir" ls-tree HEAD third-party/llvm-project | awk '{print $3}')"
[[ -n "$NPU_LLVM_SHA" ]] || die "could not read third-party/llvm-project pin from AscendNPU-IR"
echo "  derived: npuir third-party/llvm-project=$NPU_LLVM_SHA"

# 2a: inner copy inside triton-ascend (pristine; setup.py patches it at build
#     time; TA cmake builds it with BISHENGIR_BUILD_STANDALONE_IR_ONLY=ON and
#     never looks at its third-party/)
INNER_NPU="$ROOT/3rdparty/triton-ascend/third_party/ascend/AscendNPU-IR"
if ! exists_skip "$INNER_NPU/CMakeLists.txt"; then
    rm -rf "$INNER_NPU"
    place_tree "$WORK/npuir" "$INNER_NPU"
    # drop the empty submodule mount dirs: TA builds the inner npuir with
    # BISHENGIR_BUILD_STANDALONE_IR_ONLY=ON against the LLVM from step 3 and
    # never looks at npuir's own third-party/
    rm -rf "$INNER_NPU/third-party"
    write_vendor_sha "$INNER_NPU" "$NPU_IR_URL" "$NPU_IR_SHA" "pristine; 3rdparty/AscendNPU-IR.patch applied by setup.py at build time"
fi

# 2b: standalone copy + its own patched/trimmed llvm-project
if ! exists_skip "$ROOT/3rdparty/AscendNPU-IR/build-tools/build.sh"; then
    fetch_pin "$LLVM_URL" "$NPU_LLVM_SHA" "$WORK/llvm-npuir"
    banner "step 2b: pre-applying AscendNPU-IR's own llvm patches (${NPU_LLVM_SHA:0:9})"
    # faithful replay of npuir build-tools/apply_patches.sh for llvm-project
    # (sorted *.patch), but with `git apply` instead of `patch -p1 --merge`
    # so it also works under Windows git-bash (which ships no patch(1)).
    # Each patch is copied to a simple temp name first: under git-bash,
    # git.exe cannot open POSIX-style paths whose file names contain `[]`.
    (
        cd "$WORK/llvm-npuir"
        for p in "$WORK/npuir"/build-tools/patches/llvm-project/*.patch; do
            echo "  patch: $(basename "$p")"
            cp "$p" "$WORK/current.patch"
            # GNU patch tolerates a patch file whose last line lacks a
            # trailing newline; git apply rejects it ("corrupt patch at
            # line N"). Restore the newline on our throwaway copy.
            if [[ -s "$WORK/current.patch" && -n "$(tail -c 1 "$WORK/current.patch")" ]]; then
                printf '\n' >> "$WORK/current.patch"
            fi
            # Upstream replays these with `patch -p1 --merge`, whose default
            # fuzz (2) tolerates drifted context; the git-apply equivalent is
            # -C1. Try strict first, then reduced context.
            if ! git apply --ignore-whitespace "$WORK/current.patch" 2>"$WORK/apply.err"; then
                echo "  [WARN] strict apply failed for $(basename "$p"), retrying with -C1 (GNU-patch fuzz equivalent)"
                if ! git apply --ignore-whitespace -C1 "$WORK/current.patch" 2>>"$WORK/apply.err"; then
                    cat "$WORK/apply.err" >&2
                    die "patch $(basename "$p") does not apply to llvm-project@$NPU_LLVM_SHA"
                fi
            fi
        done
        rm -f "$WORK/current.patch"
    )
    capture_exec_list "$WORK/llvm-npuir" "$WORK/exec-llvm-npuir.list"
    trim_llvm_tree "$WORK/llvm-npuir"
    place_tree "$WORK/npuir" "$ROOT/3rdparty/AscendNPU-IR"
    rm -rf "$WORK/llvm-npuir/.git"
    # the npuir checkout carries EMPTY submodule mount dirs (third-party/
    # {llvm-project,torch-mlir}); an existing empty dir would make `mv` nest
    # the tree one level too deep, and torch-mlir must stay absent
    rm -rf "$ROOT/3rdparty/AscendNPU-IR/third-party"
    mkdir -p "$ROOT/3rdparty/AscendNPU-IR/third-party"
    mv "$WORK/llvm-npuir" "$ROOT/3rdparty/AscendNPU-IR/third-party/llvm-project"
    write_vendor_sha "$ROOT/3rdparty/AscendNPU-IR" "$NPU_IR_URL" "$NPU_IR_SHA" "bishengir patches PRE-APPLIED to third-party/llvm-project; build WITHOUT --apply-patches; torch-mlir intentionally absent"
    write_vendor_sha "$ROOT/3rdparty/AscendNPU-IR/third-party/llvm-project" "$LLVM_URL" "$NPU_LLVM_SHA" "npuir build-tools/patches/llvm-project/*.patch pre-applied; trimmed to llvm+mlir+lld, no tests"
fi

# ---------------------------------------------------------------------------
# step 3: LLVM for triton itself (fad3272 + triton-ascend's llvm patch)
# ---------------------------------------------------------------------------
banner "step 3: llvm-project @ ${LLVM_SHA:0:9} (patch: $(basename "$LLVM_PATCH"))"
if ! exists_skip "$ROOT/3rdparty/llvm-project/llvm/CMakeLists.txt"; then
    fetch_pin "$LLVM_URL" "$LLVM_SHA" "$WORK/llvm-ta"
    # --ignore-whitespace: the upstream patch has trailing whitespace in some
    # context lines (plain `git apply` rejects it)
    git -C "$WORK/llvm-ta" apply --ignore-whitespace "$LLVM_PATCH"
    echo "  patched files: $(git -C "$WORK/llvm-ta" diff --name-only | wc -l)"
    capture_exec_list "$WORK/llvm-ta" "$WORK/exec-llvm-ta.list"
    trim_llvm_tree "$WORK/llvm-ta"
    place_tree "$WORK/llvm-ta" "$ROOT/3rdparty/llvm-project"
    write_vendor_sha "$ROOT/3rdparty/llvm-project" "$LLVM_URL" "$LLVM_SHA" "$(basename "$LLVM_PATCH") PRE-APPLIED; trimmed to llvm+mlir+lld, no tests; build with -DLLVM_INCLUDE_TESTS=OFF -DMLIR_INCLUDE_TESTS=OFF"
fi

# ---------------------------------------------------------------------------
# step 4: shmem (ACLSHMEM)
# ---------------------------------------------------------------------------
banner "step 4: shmem @ ${SHMEM_SHA:0:9}"
if ! exists_skip "$ROOT/3rdparty/shmem/scripts/build.sh"; then
    fetch_pin "$SHMEM_URL" "$SHMEM_SHA" "$WORK/shmem"
    capture_exec_list "$WORK/shmem" "$WORK/exec-shmem.list"
    place_tree "$WORK/shmem" "$ROOT/3rdparty/shmem"
    write_vendor_sha "$ROOT/3rdparty/shmem" "$SHMEM_URL" "$SHMEM_SHA" "pristine; -python_extension path is download-free"
fi

# ---------------------------------------------------------------------------
# step 5: nlohmann/json headers (JSON_SYSPATH for setup.py offline mode)
# ---------------------------------------------------------------------------
banner "step 5: nlohmann/json v$JSON_VERSION"
if ! exists_skip "$ROOT/3rdparty/nlohmann-json/include/nlohmann/json.hpp"; then
    curl -fsSL "$JSON_URL" -o "$WORK/json-include.zip"
    "$PYTHON_BIN" -m zipfile -e "$WORK/json-include.zip" "$WORK/json"
    rm -rf "$ROOT/3rdparty/nlohmann-json"
    mkdir -p "$ROOT/3rdparty/nlohmann-json"
    cp -a "$WORK/json/include" "$ROOT/3rdparty/nlohmann-json/include"
    cp -a "$WORK/json/single_include" "$ROOT/3rdparty/nlohmann-json/single_include"
    cp -a "$WORK/json/LICENSE.MIT" "$ROOT/3rdparty/nlohmann-json/LICENSE.MIT"
    write_vendor_sha "$ROOT/3rdparty/nlohmann-json" "$JSON_URL" "v$JSON_VERSION" "release include.zip; JSON_SYSPATH for TRITON_OFFLINE_BUILD"
fi

# ---------------------------------------------------------------------------
# step 6: repo hygiene files
# ---------------------------------------------------------------------------
banner "step 6: .gitattributes + VENDORED.md"
cat > "$ROOT/3rdparty/.gitattributes" <<'EOF'
# Keep vendored sources and patches byte-identical on every platform:
# normalize to LF in the repo AND in working trees (a CRLF checkout of
# 3rdparty/*.patch makes `git apply` fail with "corrupt patch").
* text=auto eol=lf
EOF

cat > "$ROOT/3rdparty/VENDORED.md" <<EOF
# Vendored offline-build dependencies (Ascend / Atlas A3)

Regenerate with \`bash scripts/vendor_deps.sh\` on a networked Linux machine,
then commit. Consumed by \`scripts/build_ascend_a3.sh\` with **no network
access** at build time. Each tree carries a \`.vendor-sha\` provenance file.

| Path | Upstream | Commit / Version | State |
|---|---|---|
| \`llvm-project/\` | github.com/llvm/llvm-project | \`$LLVM_SHA\` | triton-ascend \`llvm_patch/$(basename "$LLVM_PATCH")\` **pre-applied**; trimmed to \`llvm/+mlir/+lld\`, test suites removed (build with \`-DLLVM_INCLUDE_TESTS=OFF -DMLIR_INCLUDE_TESTS=OFF\`; FileCheck is kept, llvm-lit is not built and not needed) |
| \`triton-ascend/\` | github.com/triton-lang/triton-ascend | \`$TA_SHA\` | pristine (submodule pin; \`3rdparty/triton-ascend.patch\` applies -- verified by vendor_deps.sh and build-step preflight; setup.py applies it at build time) |
| \`triton-ascend/third_party/ascend/AscendNPU-IR/\` | gitcode.com/Ascend/AscendNPU-IR | \`$NPU_IR_SHA\` | pristine (triton-ascend's pin; setup.py applies \`3rdparty/AscendNPU-IR.patch\`; TA cmake builds it with \`BISHENGIR_BUILD_STANDALONE_IR_ONLY=ON\`, its \`third-party/\` is not needed) |
| \`AscendNPU-IR/\` | gitcode.com/Ascend/AscendNPU-IR | \`$NPU_IR_SHA\` | standalone bisheng tool build (build-step 3); its \`third-party/llvm-project\` @ \`$NPU_LLVM_SHA\` has npuir's own \`build-tools/patches/llvm-project/*.patch\` **pre-applied** and is trimmed like above; \`third-party/torch-mlir\` intentionally absent (\`BUILD_TORCH_MLIR=OFF\`) |
| \`shmem/\` | gitcode.com/cann/shmem | \`$SHMEM_SHA\` | pristine (submodule pin; the \`-python_extension\` path of its \`scripts/build.sh\` performs no downloads -- catlass/googletest/json are only fetched by -uttests/-examples/-python_example/-full/SOC_TYPE=Ascend950) |
| \`nlohmann-json/\` | github.com/nlohmann/json release | v$JSON_VERSION | \`include/\` + \`single_include/\`; passed to setup.py via \`JSON_SYSPATH\` under \`TRITON_OFFLINE_BUILD=1\` |

Notes:

* \`3rdparty/triton-ascend\` and \`3rdparty/shmem\` are **no longer git
  submodules** (gitlinks and \`.gitmodules\` entries removed by vendor_deps.sh).
  \`3rdparty/triton\` and \`3rdparty/mori\` remain submodules for the
  NVIDIA/ROCm flows.
* \`3rdparty/.gitattributes\` forces LF everywhere so a Windows checkout can
  never corrupt the vendored trees or \`3rdparty/*.patch\`.
* The two LLVM trees are trimmed: clang/lldb/flang/libcxx/... and all
  \`test/\`+\`unittests/\` directories are absent. This is safe because the
  builds only enable \`mlir;llvm;lld\` (resp. \`mlir\`) and pass
  \`*_INCLUDE_TESTS=OFF\`; FileCheck lives under \`llvm/utils\` (gated by
  \`LLVM_INCLUDE_UTILS\`, default ON) and is still built+installed. The
  \`mlir-doc\` target that setup.py builds comes from the *installed*
  \`MLIRConfig.cmake\` (an empty aggregator target), not from the source tree.
* Vendored on: $(date -u +%Y-%m-%dT%H:%M:%SZ) by scripts/vendor_deps.sh
EOF

# ---------------------------------------------------------------------------
# step 7: stage everything (-f: root .gitignore has broad patterns like
#         `build`, `*.csv`, `tmp*` that would silently drop upstream files)
# ---------------------------------------------------------------------------
banner "step 7: git add -f (this touches ~50k files, be patient)"
cd "$ROOT"
git add -f -A \
    3rdparty/llvm-project \
    3rdparty/triton-ascend \
    3rdparty/AscendNPU-IR \
    3rdparty/shmem \
    3rdparty/nlohmann-json \
    3rdparty/VENDORED.md \
    3rdparty/.gitattributes \
    .gitattributes \
    .gitmodules

# Windows checkouts/adds lose the exec bit (core.fileMode=false); restore the
# upstream 100755 modes in the index so Linux clones get runnable scripts
# (e.g. AscendNPU-IR/build-tools/*.sh). No-ops for trees that were skipped.
banner "step 7b: restoring upstream exec bits in the index"
apply_exec_bits "$WORK/exec-ta.list"        "3rdparty/triton-ascend"
apply_exec_bits "$WORK/exec-npuir.list"     "3rdparty/triton-ascend/third_party/ascend/AscendNPU-IR"
apply_exec_bits "$WORK/exec-npuir.list"     "3rdparty/AscendNPU-IR"
apply_exec_bits "$WORK/exec-llvm-npuir.list" "3rdparty/AscendNPU-IR/third-party/llvm-project"
apply_exec_bits "$WORK/exec-llvm-ta.list"   "3rdparty/llvm-project"
apply_exec_bits "$WORK/exec-shmem.list"     "3rdparty/shmem"

# ---------------------------------------------------------------------------
# step 8: verification
# ---------------------------------------------------------------------------
banner "step 8: verification"
fail=0
for f in \
    3rdparty/llvm-project/llvm/CMakeLists.txt \
    3rdparty/llvm-project/mlir/CMakeLists.txt \
    3rdparty/llvm-project/lld/CMakeLists.txt \
    3rdparty/llvm-project/mlir/lib/Dialect/SCF/IR/SCF.cpp \
    3rdparty/triton-ascend/cmake/llvm-hash.txt \
    3rdparty/triton-ascend/third_party/ascend/AscendNPU-IR/CMakeLists.txt \
    3rdparty/AscendNPU-IR/build-tools/build.sh \
    3rdparty/AscendNPU-IR/CMakeLists.txt \
    3rdparty/AscendNPU-IR/bishengir/include \
    3rdparty/AscendNPU-IR/third-party/llvm-project/llvm/CMakeLists.txt \
    3rdparty/shmem/scripts/build.sh \
    3rdparty/nlohmann-json/include/nlohmann/json.hpp
do
    [[ -e "$ROOT/$f" ]] && echo "  [OK] $f" || { echo "  [MISSING] $f" >&2; fail=1; }
done
# fad3272.patch really landed in the TA llvm tree?
if git -C "$ROOT" apply --reverse --check --ignore-whitespace --directory=3rdparty/llvm-project "$LLVM_PATCH" 2>/dev/null; then
    echo "  [OK] llvm-project tree carries $(basename "$LLVM_PATCH")"
else
    echo "  [WARN] could not reverse-verify $(basename "$LLVM_PATCH") on 3rdparty/llvm-project" >&2
fi
# setup.py's two patches must apply to the pristine vendored trees
if (cd "$ROOT/3rdparty/triton-ascend" && git apply --check "$ROOT/3rdparty/triton-ascend.patch"); then
    echo "  [OK] 3rdparty/triton-ascend.patch applies to vendored triton-ascend"
else
    echo "  [FAIL] 3rdparty/triton-ascend.patch does NOT apply" >&2; fail=1
fi
if (cd "$INNER_NPU" && git apply --check "$ROOT/3rdparty/AscendNPU-IR.patch"); then
    echo "  [OK] 3rdparty/AscendNPU-IR.patch applies to vendored inner AscendNPU-IR"
else
    echo "  [FAIL] 3rdparty/AscendNPU-IR.patch does NOT apply" >&2; fail=1
fi
exec_count=$(git ls-files -s 3rdparty | awk '$1=="100755"' | wc -l)
echo "  exec-bit files staged under 3rdparty/: $exec_count (expect >0, e.g. npuir build-tools/*.sh)"
[[ "$exec_count" -gt 0 ]] || fail=1
[[ "$fail" == "0" ]] || die "verification failed -- inspect the messages above"

cat <<EOF

DONE. Everything is staged. Next:

    git status
    git diff --cached --stat | tail -5
    git commit -m "vendor: offline Ascend build dependencies (see 3rdparty/VENDORED.md)"

Then build on the (offline) A3 host with:

    bash scripts/build_ascend_a3.sh
EOF
